config/routes.rb
Rails.application.routes.draw do

  class OnlyAjaxRequest
     def matches?(request)
       request.xhr?
     end
   end

  # Rutas mediante AJAX
  get 'elements/show_ajax' => 'elements#show_ajax', constraint: OnlyAjaxRequest.new
  get 'movements/get_element_ajax' => 'movements#get_element_ajax', constraint: OnlyAjaxRequest.new

  get 'movements' => 'movements#index' , as: :movements
  get 'movements/enter'
  get 'movements/exit'
  get 'movements/edit'
  get 'movements/incomplete_bin'
  post 'movements/enter_element'
  post 'movements/exit_element'
  post 'movements/update'
  post 'movements/incomplete_bin_save'

  resources :user_control_accesses
  resources :ip_addresses
  # User Control routes
  get '/user_controls/sign_in', to: 'user_controls#new_session'
  post '/user_controls/create_session'
  delete '/user_controls/sign_out', to: 'user_controls#destroy_session'
  resources :user_controls, except: [:show] do
    member do
      post :add_access# => , as: :authorize_user
      post :remove_access# => , as: :authorize_user
    end
  end

  # post '/user_controls/:id/add_access', to: 'user_controls#add_access'
  # post '/user_controls/:id/remove_access', to: 'user_controls#remove_access'

  get 'reports/index', as: :reports
  get 'reports/warehouse_report'#, as: :reports
  get 'reports/show_downloads', as: :downloads
  get 'reports/download_s3_file', as: :download_s3_file
  get 'reports/process_products_xls', as: :process_products_xls


  get 'pages/home'
  get 'pages/home_quality_controls'

  # devise_for :users
  devise_for :users, :controllers => { :sessions => "users/sessions" }
  resources :users, only: [:show, :index, :edit, :update, :destroy] do
    member do
      post :authorize# => , as: :authorize_user
      post :change_role
    end
  end
  # post '/users/authorize' => 'general#accept_invoice', as: :authorize
  # resources :drying_methods
  # resources :product_types

  resources :elements_groups do
    member do
      post :add_element# => , as: :authorize_user
      post :remove_element
    end
  end

  get 'elements/elems_in_wh_and_quality', as: :elems_in_wh_and_quality
  resources :elements
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get '/' => "elements#index"
  #get '/' => "pages#home_quality_controls"

  # resources :damage_samples
  # resources :caliber_samples
  # resources :carozo_samples
  resources :sorbate_samples
  resources :humidity_samples
  resources :group_humidity_samples



  namespace :calibrado do
    resources :caliber_samples
    resources :damage_samples
  end

  namespace :recepcion_seco do
    resources :caliber_samples
    resources :damage_samples
  end

  namespace :secado do
    resources :caliber_samples
    resources :damage_samples
  end

  namespace :seam do
    resources :caliber_samples
    resources :damage_samples
  end

  namespace :cn do
    resources :caliber_samples
    resources :damage_samples
  end

  namespace :tsc do
    resources :caliber_samples
    resources :damage_samples
    resources :carozo_samples
  end

  namespace :tcc do
    resources :caliber_samples
    resources :damage_samples
  end

  namespace :descarte do
    resources :damage_samples#, except: [:show, :destroy]
  end

  root "pages#home"

end

app/controllers/group_humidity_samples_controller.rb
class GroupHumiditySamplesController < HumiditySamplesController
  # include SamplesMethods
  # before_action :check_permissions_samples_controller_or_redirect
  # before_action :set_humidity_sample, only: [:show, :edit, :update, :destroy]
  # # Cambiarlo a solo update y destroy para disminuir la carga
  # before_action :permission_last_samples, only: [:edit, :update, :destroy]
  #
  # # GET /humidity_samples
  # def index
  #   @humidity_samples = HumiditySample.all.includes(:element)#.active
  #   @humidity_samples = @humidity_samples.page(params[:page]).ord
  # end
  #
  # # GET /humidity_samples/1
  # def show
  # end
  #
  # # GET /humidity_samples/new
  # def new
  #   @humidity_samples = HumiditySample.get_recent_samples(logged_user.name).first(3)
  #   @humidity_sample = HumiditySample.new
  #   # Permite mostrar mensaje de exito en Creación/edicion muestra anterior
  #   @success_sample = HumiditySample.find(params[:success_id]) if params[:success_id]
  # end
  #
  # # GET /humidity_samples/1/edit
  # def edit
  # end

  # POST /humidity_samples
  def create #TESTEAR
    @humidity_sample = HumiditySample.new(new_humidity_sample_params)

    if @humidity_sample.save
      logger.info "Creada muestra grupal de humidity sample"
      session[:display_created_alert] = true
      redirect_to(action: 'new', success_id: @humidity_sample.id) # REdirige al mismo controller
    else
      @humidity_samples = HumiditySample.get_recent_samples(logged_user.name).group_or_elem(@group_elem).first(3)
      render :new
    end

  end

  # PATCH/PUT /humidity_samples/1
  def update
    if @humidity_sample.update(humidity_sample_params)
      session[:display_updated_alert] = true
      redirect_to(action: 'new', success_id: @humidity_sample.id) # REdirige al mismo controller
    else
      render :edit
      #Esta vista se rompe completa al ingresar.
    end
  end

  # # DELETE /humidity_samples/1
  # def destroy
  #   # @humidity_sample.soft_delete
  #   @humidity_sample.destroy
  #   redirect_to humidity_samples_url, notice: 'Muestra de humedad eliminada.'
  # end

  private
    # # Use callbacks to share common setup or constraints between actions.
    # def set_humidity_sample
    #   @humidity_sample = HumiditySample.find(params[:id])
    # end
    #
    def new_humidity_sample_params
      params.require(:humidity_sample).permit(:responsable, :humidity, :elements_group_id)
    end
    #
    # def element_params
    #   params.permit(:tag)
    # end
    #
    # def permission_last_samples
    #   return true if user_type != "UserControl"
    #   if !HumiditySample.in_user_last_samples(@humidity_sample, logged_user.name, 3, @process)
    #     redirect_to root_path, alert: not_allowed
    #   end
    # end

  end

app/helpers/group_humidity_samples_helper.rb
module GroupHumiditySamplesHelper
end

app/views/group_humidity_samples/_form_new.html.erb
<% if humidity_sample.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(humidity_sample.errors.count, "error") %> prohibited this humidity_sample from being saved:</h2>
  <ul>
    <% humidity_sample.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>


<div class= "container-samples">
  <div class= "pestaña">Laboratorio</div>
    <div class="outside-new-form green-outside-new-form">
      <h1><span class= "glyphicon glyphicon-list-alt"></span> Humedad de Grupo</h1>

<% url = group_humidity_samples_path %>
<% method = set_form_method("new")%>
<%= form_for(humidity_sample, url: url, method: method, html: {class: 'inside-new-form validatable'})  do |f| %>

  <%= f.hidden_field :responsable, value: logged_user.name %>

  <div class="field">
    <%= f.label :tarjas  %>
    <%= field_elements_group(f, 'new', "", humidity_sample)%>
  </div>

  <div class="field">
    <%= f.label :"humedad (%)" %>
    <%= f.number_field :humidity, step: 0.01, min:0 %>

  </div>

  <div class="actions">
    <%= f.submit "Guardar",  class: "btn btn-primary btn-lg btn-block" %>
  </div>
<% end %>


    </div>
  </div>
</div>

app/views/group_humidity_samples/edit.html.erb
<% if @humidity_sample.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@humidity_sample.errors.count, "error") %> prohibited this humidity_sample from being saved:</h2>
  <ul>
    <% @humidity_sample.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>


<div class= "container-samples">
  <div class= "pestaña">Laboratorio</div>
    <div class="outside-new-form ">
      <h1><span class= "glyphicon glyphicon-list-alt"></span> Editar Humedad de grupo</h1>

<% url = "/group_humidity_samples/#{@humidity_sample.id}" %>
<% method = set_form_method("edit")%>
<%= form_for(@humidity_sample, url: url, method: method, html: {class: 'inside-new-form validatable ', autocomplete: :off})  do |f| %>

<div class="field">
  <%= f.label :tarjas  %>
  <%= field_elements_group(f, 'edit', "", @humidity_sample)%>
</div>
  <div class="field">
    <%= f.label :editar_humedad %>
    <%= f.number_field :humidity, step: 0.01, min:0 %>
  </div>


  <div class="buttons-together-edit">
    <%= link_to 'Regresar', :back, class: "btn-back btn btn-primary btn-lg "%>
    <%= f.submit "Editar", class: "btn-edit btn btn-warning btn-lg" %>
  </div>

<% end %>


    </div>
  </div>
</div>

app/views/group_humidity_samples/index.html.erb
<div class="container">
<h1>Muestras de Humedad Grupal</h1>
<%= paginate @humidity_samples %>
<table class = "table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Creación</th>
      <th>Responsable</th>
      <th>Grupo de tarjas</th>
      <th>Humedad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @humidity_samples.each do |humidity_sample| %>
        <tr>
        <td><%= humidity_sample.counter %></td>
        <td><%= date_time(humidity_sample.created_at) %></td>
        <td><%= humidity_sample.responsable %></td>
        <td><%= group_link(humidity_sample.group) %></td>
        <td><%= humidity_sample.humidity %></td>
        
        <%if access_edit_delete_sample_button%>
          <td><%= link_to 'Editar', edit_group_humidity_sample_path(humidity_sample),  class: "btn btn-warning btn-xs" %></td>
          <td><%= link_to 'Eliminar', group_humidity_sample_path(humidity_sample), method: :delete, data: { confirm: '¿Seguro que deseas eliminar la muestra?' },  class: "btn btn-danger btn-xs" %></td>

        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Ingresar muestra de humedad grupal', new_group_humidity_sample_path,  class: "btn btn-primary btn-xs" %>
</div>

app/views/group_humidity_samples/new.html.erb
<%= render 'shared/message_success_js', sample: @success_sample if  @success_sample%>
<%= render 'form_new', humidity_sample: @humidity_sample %>

<div class="container-last-samples humidity">
  <h3>Tus ultimas muestras de humedad Grupal</h3>
<table class = "table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Grupo Tarjas</th>
      <th>Resp.</th>
      <th>H (%)</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @humidity_samples.each do |humidity_sample| %>
      <tr>
        <td><%= time(humidity_sample.created_at)%></td>
        <td><%= group_link(humidity_sample.group) %></td>
        <td><%= humidity_sample.responsable.truncate(12) %></td>
        <td><%= humidity_sample.humidity %></td>

        <td><%= link_to 'Editar', edit_group_humidity_sample_path(humidity_sample),  class: "btn btn-warning btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Todas las muestras de humedad grupal', group_humidity_samples_path,  class: "btn btn-primary btn-xs" %>
</div>