config/routes.rb
Rails.application.routes.draw do

  class OnlyAjaxRequest
     def matches?(request)
       request.xhr?
     end
   end

  # Rutas mediante AJAX
  get 'elements/show_ajax' => 'elements#show_ajax', constraint: OnlyAjaxRequest.new
  get 'movements/get_element_ajax' => 'movements#get_element_ajax', constraint: OnlyAjaxRequest.new

  get 'movements' => 'movements#index' , as: :movements
  get 'movements/enter'
  get 'movements/exit'
  get 'movements/edit'
  get 'movements/incomplete_bin'
  post 'movements/enter_element'
  post 'movements/exit_element'
  post 'movements/update'
  post 'movements/incomplete_bin_save'

  resources :user_control_accesses
  resources :ip_addresses
  # User Control routes
  get '/user_controls/sign_in', to: 'user_controls#new_session'
  post '/user_controls/create_session'
  delete '/user_controls/sign_out', to: 'user_controls#destroy_session'
  resources :user_controls, except: [:show] do
    member do
      post :add_access# => , as: :authorize_user
      post :remove_access# => , as: :authorize_user
    end
  end

  # post '/user_controls/:id/add_access', to: 'user_controls#add_access'
  # post '/user_controls/:id/remove_access', to: 'user_controls#remove_access'

  get 'reports/index', as: :reports
  get 'reports/warehouse_report'#, as: :reports
  get 'reports/show_downloads', as: :downloads
  get 'reports/download_s3_file', as: :download_s3_file
  get 'reports/process_products_xls', as: :process_products_xls


  get 'pages/home'
  get 'pages/home_quality_controls'

  # devise_for :users
  devise_for :users, :controllers => { :sessions => "users/sessions" }
  resources :users, only: [:show, :index, :edit, :update, :destroy] do
    member do
      post :authorize# => , as: :authorize_user
      post :change_role
    end
  end
  # post '/users/authorize' => 'general#accept_invoice', as: :authorize
  # resources :drying_methods
  # resources :product_types

  resources :elements_groups do
    member do
      post :add_element# => , as: :authorize_user
      post :remove_element
    end
  end

  get 'elements/elems_in_wh_and_quality', as: :elems_in_wh_and_quality
  resources :elements
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get '/' => "elements#index"
  #get '/' => "pages#home_quality_controls"

  # resources :damage_samples
  # resources :caliber_samples
  # resources :carozo_samples
  resources :sorbate_samples
  resources :humidity_samples
  resources :group_humidity_samples



  namespace :calibrado do
    resources :caliber_samples
    resources :damage_samples
  end

  namespace :recepcion_seco do
    resources :caliber_samples
    resources :damage_samples
  end

  namespace :secado do
    resources :caliber_samples
    resources :damage_samples
  end

  namespace :seam do
    resources :caliber_samples
    resources :damage_samples
  end

  namespace :cn do
    resources :caliber_samples
    resources :damage_samples
  end

  namespace :tsc do
    resources :caliber_samples
    resources :damage_samples
    resources :carozo_samples
  end

  namespace :tcc do
    resources :caliber_samples
    resources :damage_samples
  end

  namespace :descarte do
    resources :damage_samples#, except: [:show, :destroy]
  end

  root "pages#home"

end

app/models/caliber_sample.rb
class CaliberSample < ApplicationRecord
  include SoftDeletable
  include AllSamplesMethods
  include Methods
  include RefreshSamplesAverages

  belongs_to :element, optional: true
  belongs_to :elements_group, optional: true
  alias_attribute :group, :elements_group

  validate :has_element_or_group

  belongs_to :caliber
  has_one :deviation_sample, dependent: :destroy
  # delegate :product_type, :to => :element, :allow_nil => true

  before_validation :calculate_caliber

  before_create :increase_and_store_counter

  validates :responsable, :fruits_per_pound, :fruits_in_sample, :sample_weight, :caliber, presence: true
  validates :fruits_per_pound, :fruits_in_sample, :sample_weight, numericality: true

  ### Metodos para hacer que sea posible trabajar con elem y group ####
  #####################################################################
  def product_type
    return self.element.product_type if self.element
    return self.group.product_type if self.group
    nil
  end
  # Get all Caliber_Samples of a process
  def self.process(process)
    group_or_elem = Util.group_or_elem(process)
    product_type = ProductType.find_by_process(process) # if process = recepcion_seco, lo convierte a secado
    product_type.cal_samples(group_or_elem)
  end
  #####################################################################

  def calculate_caliber
    # NOTE Division de enteros es por defecto aproximada en cada calculo
    grams_per_lb = Rails.configuration.grams_per_lb
    self.fruits_per_pound = ((self.fruits_in_sample.to_f /  self.sample_weight) * grams_per_lb).round(0)
    self.caliber = Util.calculate_caliber(self.fruits_per_pound, self.product_type.name)
  end

  def increase_and_store_counter
    Count.increase_and_store_counter(self, "caliber_sample")
  end

  # NOTE sgts 3 Metodos adaptados para soportar elements_group
  # NOTE se asume que cuando se está en recepcion, todas las muestras son grupales
  # Process no es = pt
  # Obtiene ultimas quantity muestras de daños del process
  def self.get_samples(process, responsable = nil)
    samples = CaliberSample.process(process).active.ord
    return samples if !responsable
    samples.where(responsable: responsable)
  end

  def self.get_recent_samples(process, responsable = nil)
    t = Rails.configuration.max_sample_hrs
    samples = CaliberSample.get_samples(process, responsable)
    samples = samples.where('caliber_samples.created_at > ?', t.hours.ago)
  end

  def self.in_user_last_samples(sample, responsable, number, process = nil)
    samples = CaliberSample.process(process)
    samples = samples.where(responsable: responsable)
    .where('caliber_samples.created_at > ?', Rails.configuration.max_sample_hrs.hours.ago)
    samples = samples.ord.ids.first(number)
    # print samples
    ret = sample.id.in?(samples)
    return ret
  end


end

app/controllers/caliber_samples_controller.rb
class CaliberSamplesController < ApplicationController
  include SamplesMethods
  before_action :check_permissions_samples_controller_or_redirect
  before_action :set_caliber_sample, only: [:show, :edit, :update, :destroy]
  before_action :set_process
  # Cambiarlo a solo update y destroy para disminuir la carga
  before_action :permission_last_samples, only: [:edit, :update, :destroy]
  before_action :set_sample_name, only: [:new, :edit]
  before_action :include_deviation, only: [:show, :new, :create, :edit, :update]

  # GET /caliber_samples
  def index
    @caliber_samples = CaliberSample.get_samples(@process)
    @caliber_samples = @caliber_samples.page(params[:page]).ord
  end

  # GET /caliber_samples/1
  def show
  end

  # GET /caliber_samples/new
  def new
    @caliber_samples = CaliberSample.get_recent_samples(@process, logged_user.name).first(3)
    @caliber_sample = CaliberSample.new
    @d_sample =  DeviationSample.new # Unicamente para que no se caiga al tratar de leer errores
    # Permite mostrar mensaje de exito en Creación/edicion muestra anterior
    @success_sample = CaliberSample.find(params[:success_id]) if params[:success_id]
  end

  # GET /caliber_samples/1/edit
  def edit
  end

  # POST /caliber_samples
  def create
    @element, status = Element.create_element_if_doesnt_exist(element_params, @process)
    @caliber_sample = CaliberSample.new(caliber_sample_params)
    @caliber_sample.element = @element

    if !status # Verifica que elemento sea del proceso actual
      @caliber_samples = CaliberSample.get_recent_samples(@process, logged_user.name).first(3)
      @d_sample =  DeviationSample.new(deviation_sample_params) if @include_deviation # Para q no se caiga, pq intenta leer errores despues
      session[:display_wrong_process_alert] = true
      render :new and return
    end

    success_saving = @caliber_sample.save
    if success_saving and @include_deviation
      @d_sample =  DeviationSample.new(deviation_sample_params)
      @d_sample.caliber_sample = @caliber_sample
      success_saving = @d_sample.save
    end

    if success_saving
      session[:display_created_alert] = true
      redirect_to send("new_"+@process+"_caliber_sample_path", success_id: @caliber_sample.id)
    else
      @caliber_samples = CaliberSample.get_recent_samples(@process, logged_user.name).first(3)
      render :new
    end
  end

  # PATCH/PUT /caliber_samples/1
  def update

    if params[:tag] != @caliber_sample.element.tag
      @element, status = Element.change_element_of_sample(@caliber_sample, element_params, @process)
      if !status
        session[:display_wrong_process_alert] = true
        return render :edit
        raise "Esto no se deberia haber ejecutado"
      end
    end

    success = @caliber_sample.update(caliber_sample_params)
    if success and @caliber_sample.deviation_sample
      success = @caliber_sample.deviation_sample.update(deviation_sample_params)
    end

      if success
        session[:display_updated_alert] = true
        redirect_to send("new_"+@process+"_caliber_sample_path", success_id: @caliber_sample.id)
      else
        #Esta vista se rompe completa al ingresar.
        # render :edit
      end
  end

  # DELETE /caliber_samples/1
  def destroy
    # @caliber_sample.soft_delete
    @caliber_sample.destroy
    # redirect_to send(@process+"_caliber_samples_url"), notice: 'Muestra de calibre eliminada'
    # Hace que se caiga si se elimina desde show, pq trata de volver
    redirect_back(fallback_location: root_path, notice: 'Muestra de calibre eliminada')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_caliber_sample
      @caliber_sample = CaliberSample.find(params[:id])
    end

    def caliber_sample_params
      params.require(:caliber_sample).permit(:responsable, :fruits_in_sample, :sample_weight, :is_ex_caliber) # :is_ex_caliber es solo para TSC
    end

    def include_deviation
      @include_deviation = true
      @include_deviation = false if @process.in? ["secado", "recepcion_seco"]
    end

    def deviation_sample_params
      params.permit(:big_fruits_in_sample, :small_fruits_in_sample)
    end

    def set_process
      @process = process_name
    end
    def set_sample_name
      @sample_name = "caliber"
    end

    def element_params
      params.permit(:tag)
    end

    # Si es UserControl, puede editar o eliminar solo sus ultimas 3 muestras
    def permission_last_samples
      # NOTE Esto puede ser fuente de tiempos excesivos en el futuro
      return true if user_type != "UserControl"
      if !CaliberSample.in_user_last_samples(@caliber_sample, logged_user.name, 3, @process)
        redirect_to root_path, alert: not_allowed
      end
    end

end

app/controllers/calibrado/caliber_samples_controller.rb
class Calibrado::CaliberSamplesController < CaliberSamplesController
end

app/controllers/calibrado/damage_samples_controller.rb
class Calibrado::DamageSamplesController < DamageSamplesController
end

app/controllers/cn/caliber_samples_controller.rb
class Cn::CaliberSamplesController < CaliberSamplesController
end

app/controllers/recepcion_seco/caliber_samples_controller.rb
class RecepcionSeco::CaliberSamplesController <  CaliberSamplesController#ApplicationController
  # include SamplesMethods
  # before_action :check_permissions_samples_controller_or_redirect
  # before_action :set_caliber_sample, only: [:show, :edit, :update, :destroy]
  # before_action :set_process
  # # Cambiarlo a solo update y destroy para disminuir la carga
  # before_action :permission_last_samples, only: [:edit, :update, :destroy]
  # before_action :set_sample_name, only: [:new, :edit]
  #
  # # GET /caliber_samples
  # def index
  #   @caliber_samples = CaliberSample.get_samples(@process)
  #   @caliber_samples = @caliber_samples.page(params[:page]).ord
  # end
  #
  # # GET /caliber_samples/1
  # def show
  # end

  # GET /caliber_samples/new
  # def new # Inherited from CaliberSamplesController
  #   @caliber_samples = CaliberSample.get_recent_samples(@process, logged_user.name).first(3)
  #   @caliber_sample = CaliberSample.new
  #   @d_sample =  DeviationSample.new # Unicamente para que no se caiga al tratar de leer errores
  #   # Permite mostrar mensaje de exito en Creación/edicion muestra anterior
  #   @success_sample = CaliberSample.find(params[:success_id]) if params[:success_id]
  # end


  # # GET /caliber_samples/1/edit
  # def edit # Inherited from CaliberSamplesController
  # end

  # POST /caliber_samples
  def create
    @caliber_sample = CaliberSample.new(caliber_sample_params)

    if @caliber_sample.save
      logger.info "Creada muestra grupal de caliber sample"
      # pp @caliber_sample
      session[:display_created_alert] = true
      redirect_to send("new_"+@process+"_caliber_sample_path", success_id: @caliber_sample.id)
    else
      @caliber_samples = CaliberSample.get_recent_samples(@process, logged_user.name).first(3)
      render :new
    end
  end

  # PATCH/PUT /caliber_samples/1
  def update
    if @caliber_sample.update(edit_caliber_sample_params)
      session[:display_updated_alert] = true
      redirect_to send("new_"+@process+"_caliber_sample_path", success_id: @caliber_sample.id)
    else
      #Esta vista se rompe completa al ingresar.
      # render :edit
    end
  end

  # # DELETE /caliber_samples/1
  # def destroy # Inherited from CaliberSamplesController
  #   # @caliber_sample.soft_delete
  #   @caliber_sample.destroy
  #   redirect_to send(@process+"_caliber_samples_url"), notice: 'Muestra de calibre eliminada'
  # end

  private

    # def set_caliber_sample
    #   @caliber_sample = CaliberSample.find(params[:id])
    # end

    def caliber_sample_params
      params.require(:caliber_sample).permit(:responsable, :fruits_in_sample, :sample_weight,
                                              :elements_group_id)
    end
    def edit_caliber_sample_params
      params.require(:caliber_sample).permit(:responsable, :fruits_in_sample, :sample_weight)
    end

    # def include_deviation
    #   @include_deviation = true
    #   @include_deviation = false if @process == "secado"
    # end
    #
    # def deviation_sample_params
    #   params.permit(:big_fruits_in_sample, :small_fruits_in_sample)
    # end
    #
    # def set_process
    #   @process = process_name
    # end
    # def set_sample_name
    #   @sample_name = "caliber"
    # end
    #
    # def element_params
    #   params.permit(:tag)
    # end
    #
    # def permission_last_samples
    #   # NOTE Esto puede ser fuente de tiempos excesivos en el futuro
    #   return true if user_type != "UserControl"
    #   if !CaliberSample.in_user_last_samples(@caliber_sample, logged_user.name, 3, @process)
    #     redirect_to root_path, alert: not_allowed
    #   end
    # end

end

app/controllers/seam/caliber_samples_controller.rb
class Seam::CaliberSamplesController < CaliberSamplesController
end

app/controllers/secado/caliber_samples_controller.rb
class Secado::CaliberSamplesController < CaliberSamplesController
end

app/controllers/tcc/caliber_samples_controller.rb
class Tcc::CaliberSamplesController < CaliberSamplesController
end

app/controllers/tsc/caliber_samples_controller.rb
class Tsc::CaliberSamplesController < CaliberSamplesController
end

app/helpers/caliber_samples_helper.rb
module CaliberSamplesHelper

  def field_sample_weight(form)
    form.number_field :sample_weight, value: 454, readonly: true
  end

  def field_big_fruits_in_sample(type, cal_sample, default = nil)
    default ||= ""
    value = type == "edit" ? cal_sample.deviation_sample.big_fruits_in_sample : default
    number_field_tag :big_fruits_in_sample, value,  placeholder: ' cantidad en 283g', min:0
  end

  def field_small_fruits_in_sample(type, cal_sample, default = nil)
    default ||= ""
    value = type == "edit" ? cal_sample.deviation_sample.small_fruits_in_sample : default
    number_field_tag :small_fruits_in_sample, value, placeholder: ' cantidad en 283g', min:0
  end

end

app/helpers/calibrado/caliber_samples_helper.rb
module Calibrado::CaliberSamplesHelper
end

app/helpers/calibrado/damage_samples_helper.rb
module Calibrado::DamageSamplesHelper
end

app/helpers/cn/caliber_samples_helper.rb
module Cn::CaliberSamplesHelper
end

app/helpers/recepcion_seco/caliber_samples_helper.rb
module RecepcionSeco::CaliberSamplesHelper
end

app/helpers/seam/caliber_samples_helper.rb
module Seam::CaliberSamplesHelper
end

app/helpers/secado/caliber_samples_helper.rb
module Secado::CaliberSamplesHelper
end

app/helpers/tcc/caliber_samples_helper.rb
module Tcc::CaliberSamplesHelper
end

app/helpers/tsc/caliber_samples_helper.rb
module Tsc::CaliberSamplesHelper
end

app/views/calibrado/caliber_samples/_form.html.erb
  <% url = set_url_for_form(type, caliber_sample) %>
  <% method =  set_form_method(type)%>

  <%= form_for(caliber_sample,  url: url, method: method, html: {class: 'inside-new-form validatable'}) do |f| %>
  <!-- , autocomplete: :off -->

    <%= f.hidden_field :responsable, value: logged_user.name %>

    <div class="field">
      <%= f.label :tarja  %>
      <%= field_tag(type, "", caliber_sample)%>
    </div>

    <div class="field">
      <%= f.label :"peso_muestra (g)" %>
      <%= field_sample_weight(f) %>
    </div>
    <div class="field">
      <%= f.label :frutos_en_muestra %>
      <%= f.number_field :fruits_in_sample, min:0 %>
    </div>


    <% if @include_deviation%>
    <p>------------------ Desviación (en 2.830g) -----------------</p>
        <div class="field">
          <%= f.label :frutos_grandes %>
          <%= field_big_fruits_in_sample(type, caliber_sample) %>
        </div>

        <div class="field">
          <%= f.label :frutos_pequeños %>
          <%= field_small_fruits_in_sample(type, caliber_sample) %>
        </div>

    <% end %>

    <%= render 'shared/buttons', f: f, form_type: type%>
  <% end %>

app/views/calibrado/caliber_samples/edit.html.erb
<%=
render 'shared_caliber_samples/edit',
  caliber_sample: @caliber_sample,
  element: @element, # Esto es por si hubo error con el element
  type: "edit"
  %>

app/views/calibrado/caliber_samples/index.html.erb
<div class="container">
<h1>Muestras de Calibre</h1>
<%= paginate @caliber_samples %>
<table class = "table table-striped">
  <thead>
    <tr>
      <!-- TODO: Considerar omitir frutos en muestra y peso muestra  -->
      <th>#</th>
      <th>Creación</th>
      <th>Responsable</th>
      <th>Tarja</th>
      <th>Frutos x libra</th>
      <th>Calibre</th>
      <th>Desviación</th>
      <th>Estado</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @caliber_samples.each do |caliber_sample| %>
      <tr>
        <td><%= caliber_sample.counter %></td>
        <td><%= date_time(caliber_sample.created_at) %></td>
        <td><%= caliber_sample.responsable.truncate(14) %></td>
        <td><%= element_link(caliber_sample.element) %></td>
        <td><%= caliber_sample.fruits_per_pound %></td>
        <td><%= caliber_sample.caliber.name %></td>

        <td><%= caliber_sample.deviation_sample.deviation.round(1) if caliber_sample.deviation_sample  %></td>

        <%if caliber_sample.deviation_sample%>
          <td><%= caliber_sample.deviation_sample.status%></td>
        <%else%>
          <td>no aplica</td>
        <%end%>


        <td><%= link_to 'Ver', calibrado_caliber_sample_path(caliber_sample),  class: "btn btn-primary btn-xs" %></td>
        <%if access_edit_delete_sample_button%>
          <td><%= link_to 'Editar', edit_calibrado_caliber_sample_path(caliber_sample),  class: "btn btn-warning btn-xs" %></td>
          <td><%= link_to 'Eliminar', calibrado_caliber_sample_path(caliber_sample), method: :delete, data: { confirm: '¿Seguro que deseas eliminar la muestra?' },  class: "btn btn-danger btn-xs" %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva muestra de calibre', new_calibrado_caliber_sample_path,  class: "btn btn-primary btn-xs" %>
</div>

app/views/calibrado/caliber_samples/new.html.erb
<%= render 'shared/message_success_js', sample: @success_sample if  @success_sample%>
<%= render 'shared/message_wrong_process_error_js', tag: @element.tag if session[:display_wrong_process_alert]%>
<%= render 'shared/errors', sample: @caliber_sample%>
<!-- Errores que poseen las deviation samples, si es que hay -->
<% if @include_deviation and @d_sample.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@d_sample.errors.count, "error") %> prohibited this deviation_sample from being saved:</h2>

  <ul>
    <% @d_sample.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= render 'shared_caliber_samples/form_calling', caliber_sample: @caliber_sample, type: "new"%>


<div class="container-last-samples caliber">
  <h3>Tus ultimas muestras de calibre</h3>
<table class = "table table-striped">
  <thead>
    <tr>
      <th> </th>
      <th>Resp.</th>
      <th>Tarja</th>
      <th>Frutos por libra</th>
      <th>Calib.</th>
      <th>FG</th>
      <th>FP</th>
      <th>Desv</th>
      <th>Estado</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @caliber_samples.each do |caliber_sample| %>
      <tr>
        <td><%= time(caliber_sample.created_at) %></td>
        <td><%= caliber_sample.responsable.truncate(6) %></td>
        <td><%= element_link(caliber_sample.element) %></td>
        <td><%= caliber_sample.fruits_per_pound %></td>
        <td><%= caliber_sample.caliber.name %></td>


        <td><%= caliber_sample.deviation_sample.big_fruits_in_sample if caliber_sample.deviation_sample %></td>
        <td><%= caliber_sample.deviation_sample.small_fruits_in_sample if caliber_sample.deviation_sample %></td>
        <td><%= caliber_sample.deviation_sample.deviation.round(1) if caliber_sample.deviation_sample  %></td>

        <%if caliber_sample.deviation_sample%>
          <td><%= short_status(caliber_sample.deviation_sample)%></td>
        <%else%>
          <td>-</td>
        <%end%>

        <td><%= link_to 'Ver', calibrado_caliber_sample_path(caliber_sample),  class: "btn btn-primary btn-xs" %></td>
        <td><%= link_to 'Editar', edit_calibrado_caliber_sample_path(caliber_sample),  class: "btn btn-warning btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Todas las muestras de calibre', calibrado_caliber_samples_path,  class: "btn btn-primary btn-xs" %>
</div>

app/views/calibrado/caliber_samples/show.html.erb
<p>
  <strong>Creación:</strong>
  <%= date_time(@caliber_sample.created_at) %>
</p>

<p>
  <strong>Responsable:</strong>
  <%= @caliber_sample.responsable %>
</p>

<p>
  <strong>Tarja:</strong>
  <%= @caliber_sample.element.tag %>
</p>

<p>
  <strong>Peso muestra:</strong>
  <%= @caliber_sample.sample_weight %>
</p>
<p>
  <strong>Frutos en muestra:</strong>
  <%= @caliber_sample.fruits_in_sample %>
</p>

<p>
  <strong>Frutos por libra:</strong>
  <%= @caliber_sample.fruits_per_pound %>
</p>

<p>
  <strong>Calibre:</strong>
  <%= @caliber_sample.caliber.name %>
</p>


<% if @include_deviation%>
  -------------- Desviacion --------------- <br>
  <p>
    <strong>Frutos grandes en muestra:</strong>
    <%= @caliber_sample.deviation_sample.big_fruits_in_sample %>
  </p>
  <p>
      <strong>Frutos pequeños en muestra:</strong>
    <%= @caliber_sample.deviation_sample.small_fruits_in_sample %>
  </p>
  <p>
    <strong>Desviacion:</strong>
    <%= @caliber_sample.deviation_sample.deviation %>
  </p>
  <p>
    <strong>Estado:</strong>
    <%= @caliber_sample.deviation_sample.status %>
  </p>
  ------------------------------------------ <br>

<% end%>


<%= link_to 'Atrás', :back,  class: "btn btn-primary btn-xs" %>