config/routes.rb
Rails.application.routes.draw do

  class OnlyAjaxRequest
     def matches?(request)
       request.xhr?
     end
   end

  # Rutas mediante AJAX
  get 'elements/show_ajax' => 'elements#show_ajax', constraint: OnlyAjaxRequest.new
  get 'movements/get_element_ajax' => 'movements#get_element_ajax', constraint: OnlyAjaxRequest.new

  get 'movements' => 'movements#index' , as: :movements
  get 'movements/enter'
  get 'movements/exit'
  get 'movements/edit'
  get 'movements/incomplete_bin'
  post 'movements/enter_element'
  post 'movements/exit_element'
  post 'movements/update'
  post 'movements/incomplete_bin_save'

  resources :user_control_accesses
  resources :ip_addresses
  # User Control routes
  get '/user_controls/sign_in', to: 'user_controls#new_session'
  post '/user_controls/create_session'
  delete '/user_controls/sign_out', to: 'user_controls#destroy_session'
  resources :user_controls, except: [:show] do
    member do
      post :add_access# => , as: :authorize_user
      post :remove_access# => , as: :authorize_user
    end
  end

  # post '/user_controls/:id/add_access', to: 'user_controls#add_access'
  # post '/user_controls/:id/remove_access', to: 'user_controls#remove_access'

  get 'reports/index', as: :reports
  get 'reports/warehouse_report'#, as: :reports
  get 'reports/show_downloads', as: :downloads
  get 'reports/download_s3_file', as: :download_s3_file
  get 'reports/process_products_xls', as: :process_products_xls


  get 'pages/home'
  get 'pages/home_quality_controls'

  # devise_for :users
  devise_for :users, :controllers => { :sessions => "users/sessions" }
  resources :users, only: [:show, :index, :edit, :update, :destroy] do
    member do
      post :authorize# => , as: :authorize_user
      post :change_role
    end
  end
  # post '/users/authorize' => 'general#accept_invoice', as: :authorize
  # resources :drying_methods
  # resources :product_types

  resources :elements_groups do
    member do
      post :add_element# => , as: :authorize_user
      post :remove_element
    end
  end

  get 'elements/elems_in_wh_and_quality', as: :elems_in_wh_and_quality
  resources :elements
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get '/' => "elements#index"
  #get '/' => "pages#home_quality_controls"

  # resources :damage_samples
  # resources :caliber_samples
  # resources :carozo_samples
  resources :sorbate_samples
  resources :humidity_samples
  resources :group_humidity_samples



  namespace :calibrado do
    resources :caliber_samples
    resources :damage_samples
  end

  namespace :recepcion_seco do
    resources :caliber_samples
    resources :damage_samples
  end

  namespace :secado do
    resources :caliber_samples
    resources :damage_samples
  end

  namespace :seam do
    resources :caliber_samples
    resources :damage_samples
  end

  namespace :cn do
    resources :caliber_samples
    resources :damage_samples
  end

  namespace :tsc do
    resources :caliber_samples
    resources :damage_samples
    resources :carozo_samples
  end

  namespace :tcc do
    resources :caliber_samples
    resources :damage_samples
  end

  namespace :descarte do
    resources :damage_samples#, except: [:show, :destroy]
  end

  root "pages#home"

end

app/models/sorbate_sample.rb
class SorbateSample < ApplicationRecord
  include SoftDeletable
  include AllSamplesMethods
  include Methods
  include ProcessIndependentSamplesModels
  include SamplesModelMethods
  include RefreshSamplesAverages

  enum status: [:rechazado, :aprobado, :pendiente]

  belongs_to :element
  delegate :product_type, :to => :element, :allow_nil => true

  # before_validation :calculate_status

  validates :element, :responsable, :sorbate, presence: true #, :status
  validates :sorbate, numericality: true

  # Sorbato es independiente del producto
  def calculate_status #(No usado)
    # TODO: Hacer tests que chequeen todos los limites.
    min = Rails.configuration.min_sorbate
    max = Rails.configuration.max_sorbate
    self.status = between?(self.sorbate, min, max) ? "aprobado" : "rechazado"
  end

end

app/controllers/sorbate_samples_controller.rb
class SorbateSamplesController < ApplicationController
  include SamplesMethods
  before_action :check_permissions_samples_controller_or_redirect
  before_action :set_sorbate_sample, only: [:show, :edit, :update, :destroy]
  # Cambiarlo a solo update y destroy para disminuir la carga
  before_action :permission_last_samples, only: [:edit, :update, :destroy]

  # GET /sorbate_samples
  # GET /sorbate_samples.json
  def index
    @sorbate_samples = SorbateSample.all
    @sorbate_samples = @sorbate_samples.page(params[:page]).ord
  end

  # GET /sorbate_samples/1
  # GET /sorbate_samples/1.json
  def show
  end

  # GET /sorbate_samples/new
  def new
    @sorbate_samples = SorbateSample.get_recent_samples(logged_user.name).first(3)
    @sorbate_sample = SorbateSample.new
    # Permite mostrar mensaje de exito en Creación/edicion muestra anterior
    @success_sample = SorbateSample.find(params[:success_id]) if params[:success_id]
  end

  # GET /sorbate_samples/1/edit
  def edit
  end

  # POST /sorbate_samples
  # POST /sorbate_samples.json
  def create
    @element, status = Element.create_element_if_doesnt_exist(element_params)
    @sorbate_sample = SorbateSample.new(sorbate_sample_params)
    @sorbate_sample.element = @element

    #NOTE: No se necesita if !status, pq status identifica error no ocurrible aca
    if !status
      @sorbate_samples = SorbateSample.get_recent_samples(logged_user.name).first(3)
      session[:display_wrong_process_alert] = true
      render :new
    elsif @sorbate_sample.save
      session[:display_created_alert] = true
      redirect_to new_sorbate_sample_path success_id: @sorbate_sample.id
    else
      pp @sorbate_sample.errors
      # redirect_to new_sorbate_sample_path
      @sorbate_samples = SorbateSample.get_recent_samples(logged_user.name).first(3)
      render :new
    end


  end

  # PATCH/PUT /sorbate_samples/1
  # PATCH/PUT /sorbate_samples/1.json
  def update

    if params[:tag] != @sorbate_sample.element.tag
      @element, status = Element.change_element_of_sample(@sorbate_sample, element_params)
      #Aqui no hay process / product_type => No hay wrong process error
      if !status
        session[:display_wrong_process_alert] = true
        return render :edit
      end
    end

    if @sorbate_sample.update(sorbate_sample_params)
      session[:display_updated_alert] = true
      redirect_to new_sorbate_sample_path success_id: @sorbate_sample.id
    else
      render :edit
    end

  end

  # DELETE /sorbate_samples/1
  def destroy
    # @sorbate_sample.soft_delete
    @sorbate_sample.destroy
    # redirect_to sorbate_samples_url, notice: 'Muestra de sorbato eliminada.'
    # Hace que se caiga si se elimina desde show, pq trata de volver
    redirect_back(fallback_location: root_path, notice: 'Muestra de sorbato eliminada.')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sorbate_sample
      @sorbate_sample = SorbateSample.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def sorbate_sample_params
    #   params.require(:sorbate_sample).permit(:element_id, :responsable, :sorbate, :status, :status_revised)
    # end
    def sorbate_sample_params
      params.require(:sorbate_sample).permit(:responsable, :sorbate)
    end

    def element_params
      params.permit(:tag)
    end

    def permission_last_samples
      return true if user_type != "UserControl"
      if !SorbateSample.in_user_last_samples(@sorbate_sample, logged_user.name, 3, @process)
        redirect_to root_path, alert: not_allowed
      end
    end
end

app/helpers/sorbate_samples_helper.rb
module SorbateSamplesHelper
end

app/views/sorbate_samples/_form.html.erb
<% if sorbate_sample.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(sorbate_sample.errors.count, "error") %> prohibited this sorbate_sample from being saved:</h2>

  <ul>
    <% sorbate_sample.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class= "container-samples">
  <div class= "pestaña">Laboratorio</div>
    <div class="outside-new-form">
      <h1><span class= "glyphicon glyphicon-list-alt"></span> Sorbato</h1>


<%= form_for(sorbate_sample, html: {class: 'inside-new-form validatable'}) do |f| %>

  <%= f.hidden_field :responsable, value: logged_user.name %>

  <div class="field">
    <%= f.label :Tarja %>
    <%= field_tag('new', '', sorbate_sample)%>
  </div>

  <div class="field">
    <%= f.label :"Sorbato (ppm)" %>
    <%= f.number_field :sorbate, step: 0.01, min:0 %>
  </div>

  <div class="actions">
    <%= f.submit "Guardar", class: "btn btn-primary btn-lg btn-block" %>
  </div>
<% end %>


    </div>
  </div>
</div>

app/views/sorbate_samples/edit.html.erb
<%= render 'shared/message_wrong_process_error_js', tag: @element.tag if session[:display_wrong_process_alert]%>

<% if @sorbate_sample.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@sorbate_sample.errors.count, "error") %> prohibited this sorbate_sample from being saved:</h2>
  <ul>
    <% @sorbate_sample.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>


<div class= "container-samples">
  <div class= "pestaña">Laboratorio</div>
    <div class="outside-new-form">
      <h1><span class= "glyphicon glyphicon-list-alt"></span> Editar Sorbato</h1>


<%= form_for(@sorbate_sample, html: {class: 'inside-new-form validatable', autocomplete: :off})  do |f| %>

  <div class="field">
    <%= f.label :Tarja %>
    <%= field_tag('edit', '', @sorbate_sample)%>
  </div>

  <div class="field">
    <%= f.label :Editar_Sorbato %>
    <%= f.number_field :sorbate, step: 0.01, min:0 %>

  </div>

  <div class="buttons-together-edit">
    <%= link_to 'Regresar', :back, class: "btn-back btn btn-primary btn-lg "%>
    <%= f.submit "Editar", class: "btn-edit btn btn-warning btn-lg" %>
  </div>

<% end %>

    </div>
  </div>
</div>

app/views/sorbate_samples/index.html.erb
<div class="container">

<h1>Muestras de Sorbato</h1>
<%= paginate @sorbate_samples %>
<table class = "table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Creación</th>
      <th>Responsable</th>
      <th>Tarja</th>
      <th>Sorbato</th>
      <!-- <th>Estado</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sorbate_samples.each do |sorbate_sample| %>
      <tr>
        <td><%= sorbate_sample.counter %></td>
        <td><%= date_time(sorbate_sample.created_at) %></td>
        <td><%= sorbate_sample.responsable %></td>
        <td><%= element_link(sorbate_sample.element) %></td>
        <td><%= sorbate_sample.sorbate %></td>
        <!-- <td> sorbate_sample.status </td> -->
        <td><%= link_to 'Ver', sorbate_sample,  class: "btn btn-primary btn-xs" %></td>
        <%if access_edit_delete_sample_button%>
          <td><%= link_to 'Editar', edit_sorbate_sample_path(sorbate_sample),  class: "btn btn-warning btn-xs" %></td>
          <td><%= link_to 'Eliminar', sorbate_sample, method: :delete, data: {confirm: 'Estas seguro?' },  class: "btn btn-danger btn-xs" %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Ingresar muestra de sorbato', new_sorbate_sample_path,  class: "btn btn-primary btn-xs" %>
</div>

app/views/sorbate_samples/new.html.erb
<%= render 'shared/message_success_js', sample: @success_sample if  @success_sample%>
<%= render 'shared/message_wrong_process_error_js', tag: @element.tag if session[:display_wrong_process_alert]%>
<%= render 'form', sorbate_sample: @sorbate_sample %>

<div class="container-last-samples sorbate">
  <h3>Tus ultimas muestras de Sorbato</h3>
<table class = "table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Tarja</th>
      <th>Resp.</th>
      <th>Sorbato</th>
      <!-- <th>Estado</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sorbate_samples.each do |sorbate_sample| %>
      <tr>
        <td><%= time(sorbate_sample.created_at)%></td>
        <td><%= element_link(sorbate_sample.element) %></td>
        <td><%= sorbate_sample.responsable.truncate(12) %></td>
        <td><%= sorbate_sample.sorbate %></td>
        <!-- <td> sorbate_sample.status </td> -->

        <td><%= link_to 'Editar', edit_sorbate_sample_path(sorbate_sample),  class: "btn btn-warning btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Todas las muestras de Sorbato', sorbate_samples_path,  class: "btn btn-primary btn-xs" %>
</div>

app/views/sorbate_samples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tarja:</strong>
  <%= @sorbate_sample.element.tag %>
</p>

<p>
  <strong>Responsable:</strong>
  <%= @sorbate_sample.responsable %>
</p>

<p>
  <strong>Sorbato:</strong>
  <%= @sorbate_sample.sorbate %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @sorbate_sample.status %>
</p>

<p>
  <strong>Creada:</strong>
  <%= date_time(@sorbate_sample.created_at) %>
</p>

<p>
  <strong>Ultima modificacion:</strong>
  <%= date_time(@sorbate_sample.updated_at) %>
</p>

<%=
# link_to 'Editar', edit_sorbate_sample_path(@sorbate_sample)
%> |
<%= link_to 'Atrás', :back, class: "btn btn-primary btn-xs" %>