config/routes.rb
Rails.application.routes.draw do

  class OnlyAjaxRequest
     def matches?(request)
       request.xhr?
     end
   end

  # Rutas mediante AJAX
  get 'elements/show_ajax' => 'elements#show_ajax', constraint: OnlyAjaxRequest.new
  get 'movements/get_element_ajax' => 'movements#get_element_ajax', constraint: OnlyAjaxRequest.new

  get 'movements' => 'movements#index' , as: :movements
  get 'movements/enter'
  get 'movements/exit'
  get 'movements/edit'
  get 'movements/incomplete_bin'
  post 'movements/enter_element'
  post 'movements/exit_element'
  post 'movements/update'
  post 'movements/incomplete_bin_save'

  resources :user_control_accesses
  resources :ip_addresses
  # User Control routes
  get '/user_controls/sign_in', to: 'user_controls#new_session'
  post '/user_controls/create_session'
  delete '/user_controls/sign_out', to: 'user_controls#destroy_session'
  resources :user_controls, except: [:show] do
    member do
      post :add_access# => , as: :authorize_user
      post :remove_access# => , as: :authorize_user
    end
  end

  # post '/user_controls/:id/add_access', to: 'user_controls#add_access'
  # post '/user_controls/:id/remove_access', to: 'user_controls#remove_access'

  get 'reports/index', as: :reports
  get 'reports/warehouse_report'#, as: :reports
  get 'reports/show_downloads', as: :downloads
  get 'reports/download_s3_file', as: :download_s3_file
  get 'reports/process_products_xls', as: :process_products_xls


  get 'pages/home'
  get 'pages/home_quality_controls'

  # devise_for :users
  devise_for :users, :controllers => { :sessions => "users/sessions" }
  resources :users, only: [:show, :index, :edit, :update, :destroy] do
    member do
      post :authorize# => , as: :authorize_user
      post :change_role
    end
  end
  # post '/users/authorize' => 'general#accept_invoice', as: :authorize
  # resources :drying_methods
  # resources :product_types

  resources :elements_groups do
    member do
      post :add_element# => , as: :authorize_user
      post :remove_element
    end
  end

  get 'elements/elems_in_wh_and_quality', as: :elems_in_wh_and_quality
  resources :elements
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get '/' => "elements#index"
  #get '/' => "pages#home_quality_controls"

  # resources :damage_samples
  # resources :caliber_samples
  # resources :carozo_samples
  resources :sorbate_samples
  resources :humidity_samples
  resources :group_humidity_samples



  namespace :calibrado do
    resources :caliber_samples
    resources :damage_samples
  end

  namespace :recepcion_seco do
    resources :caliber_samples
    resources :damage_samples
  end

  namespace :secado do
    resources :caliber_samples
    resources :damage_samples
  end

  namespace :seam do
    resources :caliber_samples
    resources :damage_samples
  end

  namespace :cn do
    resources :caliber_samples
    resources :damage_samples
  end

  namespace :tsc do
    resources :caliber_samples
    resources :damage_samples
    resources :carozo_samples
  end

  namespace :tcc do
    resources :caliber_samples
    resources :damage_samples
  end

  namespace :descarte do
    resources :damage_samples#, except: [:show, :destroy]
  end

  root "pages#home"

end

app/controllers/ip_addresses_controller.rb
class IpAddressesController < ApplicationController
  before_action :check_permissions
  before_action :set_ip_address, only: [:show, :edit, :update, :destroy]
  before_action :set_my_ip

  # GET /ip_addresses
  def index
    @ip_addresses = IpAddress.all
  end

  # GET /ip_addresses/new
  def new
    @ip_address = IpAddress.new
  end

  # POST /ip_addresses
  def create
    @ip_address = IpAddress.new(ip_address_params)
    if @ip_address.save
      redirect_to ip_addresses_url, notice: 'Ip address creada correctamente.'
    else
      render :new
    end
  end

  # DELETE /ip_addresses/1
  def destroy
    @ip_address.destroy
    redirect_to ip_addresses_url, notice: 'Ip address was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ip_address
      @ip_address = IpAddress.find(params[:id])
      @my_ip = request.remote_ip
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ip_address_params
      params.require(:ip_address).permit(:ip, :comment)
    end

    def set_my_ip
      @my_ip = request.remote_ip
    end

    def check_permissions
      return if can_access_all_ip?
      redirect_to root_path, alert: not_allowed
    end
end

app/helpers/ip_addresses_helper.rb
module IpAddressesHelper
end

app/views/ip_addresses/_form.html.erb
<br>
<%= form_for(ip_address, html: {class: 'form-basic', autocomplete: :off}) do |f| %>
<br>
  <% if ip_address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ip_address.errors.count, "error") %> prohibited this ip_address from being saved:</h2>

      <ul>
      <% ip_address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ip %>
    <%= f.text_field :ip %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_field :comment %>
  </div>

  <div class="actions">
    <%= f.submit "Guardar",  class: "btn btn-primary btn-md btn-block" %>
  </div>

  <br>
  <%= link_to 'Volver', ip_addresses_path %>
<% end %>

app/views/ip_addresses/index.html.erb
<div class="container">

<p>Tu ip es: <%=@my_ip%></p>
<h2 class = "centered">Direcciones ip autorizadas</h2>
<table class = "table table-striped">
  <thead>
    <tr>
      <th>Ip</th>
      <th>Comentario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ip_addresses.each do |ip_address| %>
      <tr>
        <td><%= ip_address.ip %></td>
        <td><%= ip_address.comment %></td>
        <td><%= link_to 'Eliminar', ip_address, method: :delete, data: { confirm: '¿Estas seguro?' },  class: "btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Agregar ip permitida', new_ip_address_path, class: "centered btn btn-primary btn-xs" %>
</div>

app/views/ip_addresses/new.html.erb
<h4 class = "centered">Agregar ip permitida (ip actual: <%=@my_ip%>)</h4>

<%= render 'form', ip_address: @ip_address %>